name: "update blog" # Name of your workflow

on:
  push:
    branches:
      - gatsby-dev # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest # Action uses Docker so only Linux is supported
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1 # Checkout your triggered branch

      - name: Install
        run: npm install

      - name: Build
        env:
          GH_API_KEY: ${{secrets.PERSONAL_KEY}}
        run: npm run build

      - name: deploy
        uses: st0ven/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PRISMIC_API_KEY: ${{secrets.PRISMIC_API_KEY}}
          BUILD_DIR: "public/"
