name: "update blog" # Name of your workflow

on:
  push:
    branches:
      - gatsby-dev # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest # Action uses Docker so only Linux is supported
    
    steps:
      - uses: actions/checkout@v1 # Checkout your triggered branch

      - name: Install
        run: npm install

      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PRISMIC_API_KEY: ${{secrets.PRISMIC_API_KEY}}
          BUILD_DIR: "public/"
        run: npm run build
